### ISSUE TITLE
stuck untuk menampilan query dari database ke view via controller

### ISSUE THREAD

**Issue by mizzcode** [mizzcode/student-crud#1]
tolong dong mas/mba yang bisa bantu untuk menampilkan hasil query . saya udah ada query di folder repository , saya bingung nya cara ngirim dari controller ke view nya bagaimana? terima kasih

**Comment by mizzcode** [comment]
wait bang

**Comment by Bahrul-Rozak** [comment]
Oke

**Comment by mizzcode** [comment]
halo mas knpa button save changes nya tidak mau di tekan pada modal add student 
![image](https://user-images.githubusercontent.com/101040281/225231131-f8638bd9-a11f-41de-b260-b1c3da100ce7.png)

dan juga pada kolom action juga tidak muncul button edit dan delete nya
![image](https://user-images.githubusercontent.com/101040281/225231364-028af7c2-3ef8-4ffd-81ec-a1c31807a024.png)

**Comment by mizzcode** [comment]
> udah solved?

belum kak, mohon bantuannya

**Comment by KEVINGILBERTTODING** [comment]
> halo mas knpa button save changes nya tidak mau di tekan pada modal add student ![image](https://user-images.githubusercontent.com/101040281/225231131-f8638bd9-a11f-41de-b260-b1c3da100ce7.png)
> 
> dan juga pada kolom action juga tidak muncul button edit dan delete nya ![image](https://user-images.githubusercontent.com/101040281/225231364-028af7c2-3ef8-4ffd-81ec-a1c31807a024.png)

type nya satu aja gan pake submit

**Comment by KEVINGILBERTTODING** [comment]
trus taruh di awal jangan di akhir

**Comment by mizzcode** [comment]
> trus taruh di awal jangan di akhir

Yg mana gan?

**Comment by Bahrul-Rozak** [comment]
Sudah solved kah?

**Comment by mizzcode** [comment]
> Sudah solved kah?

Belum mas

**Comment by mizzcode** [comment]
Terima kasih semua :)) untuk sekarang udah solved untuk add student, selanjutnya saya mau kerjain sendiri mungkin kalo ada error lagi saya bikin issue lagi . Thanks banget 👍
